services:
  api:
    container_name: user-management-api
    build: .
    ports:
      - 3000:${API_PORT}
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${API_NODE_ENV}
      - PORT=${API_PORT}
    depends_on:
      - db
    networks:
      - user-management-network
    profiles:
      - dev

  db:
    container_name: user-management-db
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - user-management-network
    volumes:
      - user-management-db-data:/var/lib/postgresql/data
    profiles:
      - dev

  test-db:
    extends:
      service: db
    container_name: user-management-test-db
    ports:
      - ${TEST_DB_PORT}:${TEST_DB_PORT}
    volumes:
      - user-management-test-db-data:/var/lib/postgresql/data
    profiles:
      - test
    command:
      - -p ${TEST_DB_PORT}

networks:
  user-management-network:
    driver: bridge

volumes:
  user-management-db-data:
  user-management-test-db-data:

